#ifndef __HAVE_CONFIG_H
#define __HAVE_CONFIG_H

#define PLAYFIELD_WIDTH (10)
#define VISIBLE_PLAYFIELD_HEIGHT (20)

#define DEFAULT_TICK_INTERVAL (100)
#define FAST_TICK_INTERVAL (DEFAULT_TICK_INTERVAL / 4)

#define QUEUE_LENGTH (3)

#define ENABLE_DISCOTIME

#define SQUARE_SIZE (30)

#define VIEWPORT_QUEUE_WIDTH (250)
#define VIEWPORT_HOLD_WIDTH (250)

#define GHOST_OPACITY (100)

#endif
